import turtle
from pickle import FALSE, TRUE
from tkinter import CENTER
wn = turtle.Screen()
wn.bgcolor('#FFF47D')
wn.title("Python Mini Project")

turtle.pensize(3)
turtle.pencolor('black')
turtle.speed('fast')

def injection():
    turtle.speed(10)
    turtle.penup()
    turtle.setpos(-290,210)
    turtle.pendown()
    turtle.right(135)
    turtle.forward(30)
    turtle.backward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.backward(20)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(30)
    turtle.backward(50)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(10)
    turtle.backward(10)
    turtle.right(90)
    turtle.forward(5)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(15)
    turtle.begin_fill()
    turtle.fillcolor('light blue')
    turtle.forward(35)
    turtle.left(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(35)
    turtle.left(90)
    turtle.forward(40)
    turtle.end_fill()
    turtle.left(90)
    turtle.backward(15)
    for i in range(5):
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.backward(10)
        turtle.right(90)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(10)
    turtle.backward(10)
    turtle.right(90)
    turtle.backward(11)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(2)
    turtle.left(90)
    turtle.forward(30)
    
def medicine():
    turtle.penup()
    turtle.right(90)
    turtle.forward(9)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(135)
    turtle.pendown()
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(80)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(15)
    turtle.begin_fill()
    turtle.fillcolor('pink')
    turtle.forward(40)
    turtle.left(45)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(11)
    turtle.left(135)
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(65)
    turtle.left(90)
    turtle.forward(70)
    turtle.end_fill()
    turtle.penup()
    turtle.left(90)
    turtle.forward(40)
    turtle.left(45)
    turtle.forward(5)
    turtle.left(45)
    turtle.forward(5)
    turtle.pendown()
    turtle.begin_fill()
    turtle.fillcolor('white')
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(30)
    turtle.end_fill()
    turtle.penup()
    turtle.backward(10)
    turtle.left(90)
    turtle.forward(12)
    turtle.pendown()
    turtle.begin_fill()
    turtle.fillcolor('red')
    for i in range(4):
        turtle.forward(8)
        turtle.right(90)
        turtle.forward(8)
        turtle.left(90)
        turtle.forward(8)
        turtle.left(90)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-236.97,239.90)
    turtle.pendown()
    turtle.begin_fill()
    turtle.fillcolor('#D3DEDC')
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(20)
    turtle.end_fill()
    turtle.left(90)
    
    
def covid():
    turtle.speed('fastest')
    turtle.pensize(1.2)
    turtle.penup()
    turtle.goto(0,250)
    turtle.pendown()
    b = 0
    while b < 200:
        turtle.color('green')
        turtle.right(b)
        turtle.forward(b)
        b = b + 1
    turtle.left(100)
    
def covid1():
    turtle.speed('fastest')
    turtle.pensize(1.2)
    turtle.penup()
    turtle.goto(0,250)
    turtle.pendown()
    b = 0
    while b < 200:
        turtle.color('blue')
        turtle.right(b)
        turtle.forward(b)
        b = b + 1
    turtle.speed('fast')
    turtle.left(100)

def mask():
    turtle.pensize(3)
    turtle.pencolor('black')
    turtle.penup()
    turtle.right(10)
    turtle.goto(200,110)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(80)
    turtle.fillcolor('#FFCC99')
    turtle.end_fill()
    turtle.penup()
    turtle.left(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(60)
    turtle.pendown()
    turtle.left(165)
    turtle.forward(15)
    turtle.begin_fill()
    turtle.fillcolor('#B7CADB')
    turtle.right(65)
    turtle.forward(70)
    turtle.left(90)
    turtle.forward(80)
    turtle.left(90)
    turtle.forward(70)
    turtle.left(90)
    turtle.forward(80)
    turtle.end_fill()
    turtle.backward(80)
    turtle.right(155)
    turtle.forward(14)
    turtle.backward(14)
    turtle.right(115)
    turtle.forward(70)
    turtle.left(65)
    turtle.forward(35)
    turtle.backward(35)
    turtle.right(155)
    turtle.forward(80)
    turtle.left(25)
    turtle.forward(40)
    turtle.left(155)
    turtle.penup()
    turtle.forward(100)
    turtle.pendown()
    turtle.begin_fill()
    turtle.fillcolor('black')
    turtle.circle(3)
    turtle.penup()
    turtle.backward(50)
    turtle.pendown()
    turtle.circle(3)
    turtle.end_fill()
    turtle.right(180)

def precautions1():
    turtle.penup()
    turtle.goto(-400,80)
    turtle.pendown()
    turtle.forward(800)
    turtle.penup()
    turtle.goto(-400,40)
    turtle.pendown()
    turtle.forward(800)
    turtle.penup()
    turtle.goto(-300,45)
    turtle.pendown()
    turtle.color('#781D42')
    turtle.write("COVID PRECAUTIONS",font=("Times New Roman",20,"normal"))

def precautions2():
    turtle.speed("slow")
    turtle.penup()
    turtle.goto(-320,-10)
    turtle.pendown()
    turtle.color('#9C0F48')
    turtle.write("=> MAINTAIN SAFE DISTANCE",font=("Verdana ",16,"normal"))
    turtle.penup()
    turtle.goto(-320,-60)
    turtle.pendown()
    turtle.write("=> WEAR MASK PROPERLY",font=("Verdana ",16,"normal"))
    turtle.penup()
    turtle.goto(-320,-110)
    turtle.pendown()
    turtle.write("=> WASH YOUR HANDS FREQUENTLY",font=("Verdana ",16,"normal"))
    turtle.penup()
    turtle.goto(-320,-160)
    turtle.pendown()
    turtle.write("=> GET VACCINATED",font=("Verdana ",16,"normal"))
    turtle.penup()
    turtle.goto(-320,-210)
    turtle.pendown()
    turtle.write("=> STAY HOME IF YOU FEEL UNWELL.",font=("Verdana ",16,"normal"))
    turtle.pendown()
    
    
turtle.penup()
turtle.goto(-110,300)
turtle.pendown()
turtle.right(90)
turtle.forward(220)
turtle.penup()
turtle.goto(110,300)
turtle.pendown()
turtle.forward(220)
turtle.left(90)

injection()
medicine()
covid()
mask()
precautions1()
precautions2()
turtle.hideturtle()
covid1()
covid()
covid1()

turtle.speed(0.5)
turtle.forward(1)
turtle.delay(1)
turtle.forward(6)

turtle.clear()

t =turtle.Turtle()
turtle.bgcolor("Light Blue")
turtle.addshape('abc.gif')
t.shape('abc.gif')
turtle.bgcolor("#FFBDE6")

turtle.done()
